### ISSUE TITLE
开放代码？

### ISSUE THREAD

**Issue by Ahacad** [slidoooor/computer_book_list#4]
作者您好，请问源代码方便开放吗，或者是否有相关 api？豆瓣的 api 寻找了一段时间没有找到

**Comment by slidoooor** [comment]
我是慢慢爬的，的确没有api，代码的话等后续我把数据补全可以放出来哈哈，但是因为是爬虫不知道允不允许

**Comment by Ahacad** [comment]
哦哦，作者辛苦了🙏
